import jwt
import time
import shrub_util.core.logging as logging


def apple_get_dev_token(team_id: str, key_id: str, key_path: str):
    with open(key_path, 'r') as f:
        private_key = f.read()
    
    headers = {
        'alg': 'ES256',
        'kid': key_id
    }
    payload = {
        'iss': team_id,
        'iat': int(time.time()),
        'exp': int(time.time()) + 3600 * 24 * 180  # 6 months
    }
    token = jwt.encode(payload, private_key, algorithm='ES256', headers=headers)
    print(token)
    return token


def apple_get_user_token(dev_token: str):
    print("getting user token")
    from flask import Flask, render_template_string, request, jsonify

    app = Flask(__name__)

    # ==============================================================================
    # PASTE YOUR DEVELOPER TOKEN HERE (The one generated by apple_music_token.py)
    # ==============================================================================
    DEVELOPER_TOKEN = dev_token

    # This is the frontend HTML/JS that will be served to the browser
    HTML_TEMPLATE = """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Apple Music Login</title>
        <!-- Load Apple's MusicKit JS v3 -->
        <script src="https://js-cdn.music.apple.com/musickit/v3/musickit.js" async></script>
        <style>
            body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh; background-color: #f5f5f7; margin: 0; }
            h1 { color: #1d1d1f; }
            button { background-color: #fa243c; color: white; border: none; padding: 15px 32px; font-weight: bold; font-size: 16px; border-radius: 8px; cursor: pointer; transition: background-color 0.3s; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
            button:hover { background-color: #d91c2e; }
            #status { margin-top: 20px; color: #555; font-size: 14px; }
        </style>
    </head>
    <body>
        <h1>Apple Music User Auth</h1>
        <button id="login-btn">Log in to Apple Music</button>
        <div id="status">Waiting for MusicKit to load...</div>

        <script>
            // Wait for MusicKit to initialize
            document.addEventListener('musickitloaded', async function() {
                const statusDiv = document.getElementById('status');
                statusDiv.innerText = 'MusicKit Loaded. Ready to login.';

                try {
                    // Configure MusicKit with your Developer Token
                    await MusicKit.configure({
                        developerToken: '{{ developer_token }}',
                        app: {
                            name: 'My Python App',
                            build: '1.0.0'
                        }
                    });
                } catch (err) {
                    statusDiv.innerText = 'Error configuring MusicKit: ' + err;
                    console.error(err);
                    return;
                }

                const music = MusicKit.getInstance();

                // Handle the login button click
                document.getElementById('login-btn').addEventListener('click', async () => {
                    statusDiv.innerText = 'Waiting for user to log in...';
                    try {
                        // This triggers the Apple sign-in popup
                        const userToken = await music.authorize();
                        statusDiv.innerText = 'Login successful! Sending token to backend...';

                        // Send the token back to our Flask backend via a POST request
                        const response = await fetch('/save-user-token', {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json'
                            },
                            body: JSON.stringify({ music_user_token: userToken })
                        });

                        const result = await response.json();
                        if(result.status === 'success') {
                            statusDiv.innerText = '✅ User Token successfully captured! Check your Python terminal.';
                        }
                    } catch (error) {
                        statusDiv.innerText = 'Login failed or was cancelled by the user.';
                        console.error("Authorization failed:", error);
                    }
                });
            });
        </script>
    </body>
    </html>
    """

    @app.route('/')
    def index():
        # Serve the HTML and inject the developer token into the Javascript
        return render_template_string(HTML_TEMPLATE, developer_token=DEVELOPER_TOKEN)

    @app.route('/save-user-token', methods=['POST'])
    def save_user_token():
        # This route catches the token sent by the Javascript `fetch` call
        data = request.json
        user_token = data.get('music_user_token')

        if user_token:
            print("\n" + "=" * 70)
            print("🎉 SUCCESS! RECEIVED MUSIC USER TOKEN:\n")
            print(user_token)
            print("=" * 70 + "\n")
            # In a real app, you would save this token to a database paired with the user's ID
            return jsonify({"status": "success", "message": "Token received"})

        return jsonify({"status": "error", "message": "No token provided"}), 400


    print("Starting server...")
    print("👉 Go to http://127.0.0.1:5000 in your web browser.")
    app.run(debug=True, port=5000)